// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/create": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/create";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/create.tsx": {
    id: "routes/create";
    page: "/create";
  };
};