// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/create": {
    params: {};
  };
  "/boards": {
    params: {};
  };
  "/board/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/create" | "/boards" | "/board/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/create.tsx": {
    id: "routes/create";
    page: "/create";
  };
  "routes/boards.tsx": {
    id: "routes/boards";
    page: "/boards";
  };
  "routes/board.tsx": {
    id: "routes/board";
    page: "/board/:id";
  };
};